spring.application.name=AICidingdemo
server.error.include-message=always

spring.datasource.url=jdbc:postgresql://localhost:5439/aicd
spring.datasource.username=postgres
spring.datasource.password=pw


spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
